language: python
python:
      - "3.7"
      - "3.8"
addons:
      apt_packages:
              - swig
              - python-dev
cache: pip

install:
      - pip install pipenv
      - pipenv install
script: 
      - pytest -v
      - PYTHONPATH=.. sphinx-build -nT -b dummy docs/ docs/_build/html
      - cd post
      - make 
      - cd create_disp_dat_c
      - make create_disp_dat
      - make test
