language: python
python:
      - "3.4"
      - "3.5"
      - "3.6"
addons:
      apt_packages:
              - swig
              - python-dev
cache: pip

install:
      - pip install -r requirements.txt
script: 
      - pytest -v --pep8
      - PYTHONPATH=.. sphinx-build -nT -b dummy docs/ docs/_build/html
      - cd post
      - make 
      - cd create_disp_dat_c
      - make create_disp_dat
      - make test
