name: Matlab CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run MATLAB Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: install MATLAB
        uses: matlab-actions/setup-matlab@v0
      - name: run tests
        uses: matlab-actions/run-tests@v0
